node/src/cli.rs, node/src/indexer/participants.rs, node/src/main.rs, node/src/tracking.rs, node/src/web.rs, node/src/web_common.rs, node/src/web_test.rs
Seems like this is very useful for debugging.
=> Bring back the debug tasks UI.

node/src/metrics.rs, node/src/sign.rs, node/src/triple.rs
Add timing metrics for triple, pre-signature, and signature generation
=> Add timing metrics for triple, pre-signature, and signature generation

Cargo.lock, node/Cargo.toml
Update minor version of rustls to address  RUSTSEC-2025-0004
=> Update minor version of rustls to address  RUSTSEC-2025-0004

node/src/db.rs
Replace magic numbers with already defined const value NONCE
=> Replace magic numbers with already defined const value NONCE

node/src/p2p.rs
Remove commented out line of code
=> Remove commented out line of code

node/src/network.rs
Make magic numbers a constants
=> Remove magic numbers from node/src/network.rs

node/src/p2p.rs
This commit addresses issue no. 7 raised by the _Trail of Bits_ audit team titled _'Skipping certificate verification introduces non-trivial modifications to TLS'_.
=> fix(audit): fix TLS certificate verification

node/src/cli.rs, node/src/p2p.rs, node/src/web.rs, pytest/tests/test_key_resharing.py, pytest/tests/test_web_endpoints.py
Also add a pytest checking that the web endpoints work.
And fix the wrong comment on the key resharing pytest.
=> Implement /health endpoint.

node/src/indexer/real.rs
=> use the main account if respond.yaml is missing

node/src/main.rs, node/src/network.rs, node/src/network/handshake.rs, node/src/p2p.rs, node/src/protocol_version.rs
See comments for details. This should resolve the issue right now that the next release introduces an incompatible change.
=> Add a protocol version and a network handshake.

node/src/assets.rs, node/src/mpc_client.rs, node/src/sign.rs, node/src/triple.rs
Closes #37. We no longer need pending_unowned/commit, because the owner persists the asset *after* succeeding in the computation, but it can only succeed if all followers succeed, but in this PR we've made all follower asset computations *include* persisting the generated asset.
=> Make asset computation follower succeed only after persisting the asset.

node/src/cli.rs, node/src/keyshare/local.rs
This PR adds two CLI commands to facilitate keyshare migration between GCP Secret Manager and local encrypted storage:
- import-keyshare: Imports a keyshare from a JSON string to local encrypted storage
- export-keyshare: Exports a keyshare from local encrypted storage to the console as JSON
**Importing a keyshare:**
```
$ CURRENT_KEYSHARE='{"epoch":1,"private_share":"1111...","public_key":"1111..."}'
$ CURRENT_LOCAL_ENCRYPTION_KEY="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
$ MPC_HOME_DIR=/path/to/mpc/home
$ mpc-node import-keyshare --home-dir "$MPC_HOME_DIR" "$CURRENT_KEYSHARE" "$CURRENT_LOCAL_ENCRYPTION_KEY"
```
**Exporting a keyshare:**
```
$ LOCAL_ENCRYPTION_KEY="AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
$ MPC_HOME_DIR=/path/to/mpc/home
$ mpc-node export-keyshare --home-dir "$MPC_HOME_DIR" …
```
=> CLI: implement import-export keyshare

node/src/cli.rs, node/src/keyshare/local.rs
=> Remove non-async version of `LocalKeyshareStorage`

node/src/cli.rs
This PR fixes the missing Tokio runtime for async import and export keyshare commands.
Adjusting the unit-tests to account for this.
Before crash:
```
Importing keyshare to local storage...
Parsed keyshare for epoch 0
thread 'main' panicked at /Users/andrei/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.44.1/src/fs/mod.rs:310:11:
there is no reactor running, must be called from the context of a Tokio 1.x runtime
stack backtrace
```
Succesful run:
```
RUST_BACKTRACE=1 cargo run -p mpc-node  import-keyshare --home-dir "$MPC_HOME_DIR" "$CURRENT_KEYSHARE" "$CURRENT_LOCAL_ENCRYPTION_KEY"
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.87s
Running `target/debug/mpc-node import-keyshare --home-dir /home/mpc_home …
```
=> Fix: tokio runtime for import/export keyshare commands

Cargo.lock, node/Cargo.toml, node/src/coordinator.rs, node/src/key_events.rs, node/src/keyshare/test_utils.rs, node/src/mpc_client.rs, node/src/network.rs, node/src/primitives.rs, node/src/providers/ecdsa/key_generation.rs, node/src/providers/ecdsa/key_resharing.rs, node/src/providers/ecdsa/mod.rs, node/src/providers/ecdsa/sign.rs, node/src/providers/ecdsa/triple.rs, node/src/providers/eddsa/key_generation.rs, node/src/providers/eddsa/key_resharing.rs, node/src/providers/eddsa/mod.rs, node/src/providers/eddsa/sign.rs, node/src/providers/mod.rs, node/src/tests/benchmark.rs, node/src/tests/mod.rs, node/src/tests/research.rs
Should be merged after https://github.com/Near-One/cait-sith/pull/12.
Add signature provider implementation for Eddsa signature scheme:
* Signing
* DKG
* Resharing 
Follow-up PR should containt:
* Further integration into the logic
* Proper e2e testing
=> Eddsa signature provider

Cargo.lock, node/Cargo.toml
Follow up after https://github.com/Near-One/cait-sith/pull/16
=> Bump cait-sith dependency 

libs/chain-signatures/contract/src/primitives/participants.rs, libs/chain-signatures/contract/src/primitives/thresholds.rs, libs/chain-signatures/contract/src/update.rs
resolves #289 
* Add tests to cover more code paths
=> Add more tests for `ThresholdParameters::validate_incoming_proposal`

.gitignore
Added IDE configs to git ignore
=> Chores: Added IDE configs to git ignore

node/src/assets.rs
resolves #320 
* Control what ids were removed from the cold queue and remove them from db too
* Add test scenario that covers the bug
=> Remove assets from db with `maybe_discard_owned`

Cargo.lock, node/Cargo.toml
See https://github.com/Near-One/cait-sith/pull/22
=> Hotfix for cait-sith memory leak.

devnet/src/cli.rs, devnet/src/loadtest.rs, devnet/src/mpc.rs, devnet/src/types.rs, pytest/tests/test_lost_assets.py
Helper command to list MPC and Loadtest setups.
Separating to keep PRs small.
=> List Mpc and Loadtest setups in devnet

libs/chain-signatures/contract/src/lib.rs, libs/chain-signatures/contract/src/tee/proposal.rs
=> feat(contract): add method to contract to get allowed image hashes

.github/workflows/ci.yml, libs/chain-signatures/contract/src/tee/proposal.rs, node/Cargo.toml, node/src/indexer/fake.rs, node/src/indexer/lib.rs, node/src/indexer/mod.rs, node/src/indexer/real.rs, node/src/indexer/tee.rs
Resolves https://github.com/near/mpc/issues/459?issue=near%7Cmpc%7C512
Also adds a feature, `tee`, to feature gate tee-related code on the node.
=> feat(indexer): Periodically fetch allowed image hashes from mpc contract

.github/workflows/docker_release.yml
test run https://github.com/near/mpc/actions/runs/15896285584
=> chore: sanitize docker build CI to replace invalid tag symbol

node/src/tests/multidomain.rs, pytest/common_lib/signature.py, pytest/tests/interactive_cluster.py
This is helpful if we need more elaborate testing, but don't want to deploy a cluster with devnet.
=> feat(pytest): interactive pytest

node/src/web.rs
Fixes https://github.com/near/mpc/issues/638
=> feat(tee): Add p2p public key to StaticWebData and http endpoint

Cargo.lock, Cargo.toml, attestation/Cargo.toml, devnet/Cargo.toml, node/Cargo.toml
Closes #650 
Follow up work needed:
#658 
#657
=> chore: use workspace for dependencies

pytest/tests/conftest.py
=> chore: update pytest build step to include `--enable-bulk-memory` flag

pytest/common_lib/contract_state.py, pytest/common_lib/shared/__init__.py, pytest/common_lib/shared/mpc_cluster.py, pytest/common_lib/shared/near_account.py, pytest/common_lib/shared/transaction_status.py, pytest/tests/test_cancellation_of_key_resharing.py
=> test: create pytest to test cancellation of key resharing

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/new_task.yml
=> chore: Override org-wide issue template

tee_launcher/config.txt, tee_launcher/launcher.py
issue found during testing:  
https://github.com/near/mpc/issues/761
fixes https://github.com/near/mpc/issues/753
=> fix(launcher): fixing of issues found during testing

libs/chain-signatures/contract/src/lib.rs, pytest/common_lib/constants.py
=> fix: increase gas limit for sign calls

Cargo.lock, devnet/Cargo.toml, devnet/src/account.rs, devnet/src/main.rs, devnet/src/mpc.rs, devnet/src/terraform.rs, devnet/src/types.rs
=> chore: remove `near_crypto` from devnet

libs/chain-signatures/contract/src/lib.rs, libs/chain-signatures/contract/src/primitives/ckd.rs, libs/chain-signatures/contract/tests/ckd.rs, libs/chain-signatures/contract/tests/common.rs
Follow up to https://github.com/near/mpc/pull/934
Should really close #929
=> fix: add domainid ckdrequest again

Cargo.lock, Cargo.toml, crates/tls/Cargo.toml, crates/tls/src/constants.rs, crates/tls/src/keygen.rs, crates/tls/src/lib.rs, crates/tls/src/tls.rs, node/Cargo.toml, node/src/p2p.rs
Resolves #945 
Stacked on #914
=> chore(node): move tls into crate

Cargo.lock, Cargo.toml
=> chore: bump version tracing-subscriber

libs/chain-signatures/contract/Cargo.toml
=> chore: upgrade `ed25519-dalek` version in contract

deployment/start.sh
https://nearone.slack.com/archives/C07UW93JVQ8/p1756970008870159?thread_ts=1756967458.561899&cid=C07UW93JVQ8
=> chore: fix deployment start script 

node/src/tests.rs
Follow-up to https://github.com/near/mpc/pull/1008#discussion_r2320121545
=> fix: use correct assert_matches

tee_launcher/launcher.py
=> chore: Set MPC authority stared by launcher to always expect real TDX HW

node/src/tests/resharing.rs
=> chore(test): fix resharing tests

docs/running_an_mpc_node_in_tdx_external_guide.md, tee_launcher/launcher_docker_compose.yaml, tee_launcher/user-config.conf
=> chore(docs): update docs after #1127

crates/contract/tests/tee.rs
=> fix: Ignore broken tests

docs/running_an_mpc_node_in_tdx_external_guide.md
fixes [1105](https://github.com/near/mpc/issues/1105)
=> docs: Update RTMR generation instructions for dstack 0.5.4

crates/contract/readme.md
This is a follow-up to address the post-merge code review comment: https://github.com/near/mpc/pull/1165#pullrequestreview-3258611343
=> docs: Update contract README with gas cost details

crates/contract/tests/inprocess/expired_attestation.rs
=> test: add grace period test for multi-node voting

crates/contract/tests/sandbox/upgrade_to_current_contract.rs
=> test: resolve flaky test caused by ordering of attestations

crates/node/src/metrics.rs, crates/node/src/providers/ecdsa/sign.rs, crates/node/src/providers/eddsa/sign.rs
=> feat: metrics tracking participant ids in failed signature computations

Cargo.lock, crates/contract/tests/sandbox/common.rs, crates/dtos_contract/Cargo.toml, crates/dtos_contract/src/crypto.rs, crates/dtos_contract/src/lib.rs, crates/node/src/trait_extensions/convert_to_contract_dto.rs, crates/test_utils/Cargo.toml
=> feat: add near_sdk compatible serde serialization for dto types + Bls types
