near/mpc

Cargo.lock
deployment/gcp-start.sh
node/Cargo.toml
node/src/cli.rs
node/src/config.rs
node/src/key_generation.rs
node/src/keyshare/gcp.rs
node/src/keyshare/local.rs
node/src/keyshare/mod.rs
node/src/main.rs
node/src/mpc_client.rs
node/src/tests/basic_cluster.rs
node/src/tests/faulty.rs

This introduces KeyshareStorage interface, with two implementations, one for local encrypted on disk, one for gcp.
They are written in a way that supports keygen and resharing. In the next PR or two, I'll be making keygen and resharing automatic, and the new key would be written via this interface. For now, keygen is still a separate command and resharing is not implemented.
We use the gcp-cloud client library which seems much better maintained than the google-secretmanager1 library used by the old MPC and has a much better interface.

Support keyshare storage in GCP and local, natively.

---

node/src/cli.rs
node/src/config.rs
node/src/indexer/handler.rs
node/src/indexer/response.rs
node/src/indexer/transaction.rs
pytest/index_signature_request.py

Implements #135.
Based on observations from the synthetic benchmark tooling, a node should use at least 1.3N keys if it wants to send N tx/s without nonce conflicts. 50 keys each on 8 nodes should be good for 300 sign requests per second. 
Given the large number of keys I chose to use a config file rather than pass them all in via an environment variable as we do for other secrets. The respond account doesn't have any special privileges so risks are lower here. Not sure exactly what would be best practice though, so open to suggestions.
The pytest gains a flag configuring the number of access keys. I confirmed via logs and via near-cli inspection that nodes spread their txs across their access keys as expected. I'm not sure I've actually managed to produce a nonce conflict in localnet …

use multiple access keys to prevent nonce conflicts

---

Cargo.lock
node/Cargo.toml

c.f. https://github.com/Near-One/cait-sith/pull/3

update k256 crate to 13.4

---

deployment/gcp-start.sh
node/src/cli.rs

Allows mpc-node generation of configs required for running near indexer.
```
➜  debug git:(initialize-near-config)  ./mpc-node init --dir near_init  --chain-id mainnet  --download-genesis
➜  debug git:(initialize-near-config)  ls near_init
total 648
drwxr-xr-x@  5 andrei  staff   160B 30 Jan 18:39 .
drwxr-xr-x  11 andrei  staff   352B 30 Jan 18:18 ..
-rw-r--r--@  1 andrei  staff   7.5K 30 Jan 18:39 config.json
-rw-r--r--@  1 andrei  staff   311K 30 Jan 18:39 genesis.json
-rw-------@  1 andrei  staff   214B 30 Jan 18:39 node_key.json
```

Option to Initialize near config

---

node/src/cli.rs
node/src/config.rs
node/src/coordinator.rs
node/src/db.rs
node/src/indexer/fake.rs
node/src/indexer/response.rs
node/src/key_generation.rs
node/src/key_resharing.rs
node/src/main.rs
node/src/metrics.rs
node/src/mpc_client.rs
node/src/network.rs
node/src/p2p.rs
node/src/primitives.rs
node/src/tests/basic_cluster.rs
node/src/tests/benchmark.rs
node/src/tests/faulty.rs
node/src/tests/mod.rs
node/src/tests/research.rs
node/src/tests/resharing.rs
node/src/triple.rs
pytest/common_lib/shared.py
pytest/exec_pytest.sh
pytest/tests/test_contract_update.py
pytest/tests/test_key_resharing.py
pytest/tests/test_parallel_sign_calls.py
pytest/tests/test_signature_request.py

This PR implement key resharing. It is expected to work out of the box as long as we manually kick the contract into a Resharing state (by sending join and vote_join; leaving is fine too). Some of the code was adapted from #87 .
Rust-side integration tests are included to test resharing behavior including signature buffering during resharing. **Python integration test as well as real cluster test are TODO**.
Along with that are a few more related or necessary changes:
* Make the coordinator always check if the current node is not a participant, and halt in this case (until contract state change) instead of failing (and then looping).
* Make the network layer's `wait_for_ready` wait for that many connections to be *bidirectionally* connected, not just outgoing. This solves a subtle problem …

Implement key resharing.

---

node/src/metrics.rs
node/src/sign_request.rs

Check if the SignRequestStorage message channel receives an error. This can occur when the number of messages in the channel overflows the capacity. If an error is encounter then the metric SIGN_REQUEST_CHANNEL_FAILED is incremented.

Check message channel for receive errors

---

.github/workflows/docker_release.yml

Constant mainnet and testnet image tags will allow automatic docker images updates for MPC nodes (with watchtower).
Now every published image will have 3 tags:
latest
brach/tag ref
brach/tag ref + commit hash

Chore: additional docker tag

---

pytest/config.json
pytest/exec_pytest.sh
pytest/readme.md

We see occasional timeouts during contract creation in the GitHub tests and I was seeing timeouts approximately in 1 in 5 runs on my mac. In exec_pytest.sh we are building the MPC code in release and linking it to a debug build of near core.
This change makes sure that we build and use the release version of near core when running the python tests.
After this change I have not observed timeouts in contract creation.

Run Near Core in release

---

node/src/metrics.rs
node/src/mpc_client.rs
node/src/network.rs
node/src/p2p.rs

Addresses #145 
Every 5 seconds each node would export connectivity metrics for all network connections

Export network connectivity metrics for each participant

---

node/src/indexer/handler.rs
node/src/indexer/mod.rs
node/src/indexer/real.rs
node/src/indexer/tx_sender.rs
node/src/indexer/tx_signer.rs
node/src/indexer/types.rs
node/src/metrics.rs

In the past we attempted to index `respond` transactions to decide whether they need to be resubmitted. That approach does not work reliably because the account making the respond call may be on a different shard than the signer contract. The node's indexer is configured to track only the shard containing the signer contract.
In this PR, we instead make a view call on `get_pending_request`. It gets executed locally by the node's indexer on the signer contract's state and lets us know whether the respond call has succeeded.
Closes #153.

retry "respond" if contract state still has pending request

---

.github/workflows/ci.yml
Cargo.lock
node/Cargo.toml
rust-toolchain.toml

update nearcore to latest testnet release

update nearcore to latest testnet release

---

node/src/p2p.rs

Force TLS 1.3 for network connections in the network library

Force TLS 1.3 for network connections

---

node/src/network.rs
node/src/network/conn.rs
node/src/p2p.rs

All cait-sith computations have no fault tolerance. In order to ensure that messages are not lost during a computation (since a single lost message would make the computation fail), we check if the TCP connections we started the computation with are the same as the TCP connections we currently have.
Previously, this was done in a couple of fragmented ways:
* When sending a message to a participant, we check if the outgoing `PersistentConnection`'s current (connection, version) tuple matches with the version we grabbed when we started the computation. If not, we fail the send (and thus abort the computation).
* When receiving a message, we check if all the participants needed for the computation are still alive, but we only check this once per second.
There are various subtle problems with …

Reimplement connectivity tracking.

---

node/src/protocol.rs

This commit addresses finding no. B7 from the Trail of Bits audit titled _'Explicit `into_iter` loop'_.

refactor(audit): remove explicit `.into_iter`

---

pytest/common_lib/contracts.py
pytest/tests/test_contract_update.py

This PR:
- fixes the pytest fixture logic for contract compilation (one pytest fixture loaded the contract before the other one compiled it)
- changes the timeout for nonce conflicts in the update pytest and increases the number of signature requests (@ashamis had a test fail, this might help)

minor fixes to pytest 

---

deployment/gcp-start.sh

This allows flexibility for local environments. 
In case either is missing, both configs get overwritten. We want to avoid this and allow separate config customizations

Chores: separate init config for mpc and near

---

node/src/config.rs
node/src/indexer/real.rs
pytest/common_lib/shared.py
pytest/tests/test_without_respond_yaml.py

This PR follows up #219, in which `respond.yaml` was made optional:
> I'd prefer if load_respond_config_file returned a Result<Option<...>> where if the file doesn't exist it is explicitly returned as an Option::None. The reason is that it can be easy to make a mistake in the yaml syntax and cause the config to fail to deserialize, and yet it would almost silently fall back to single account.
A pytest is also added to verify that nodes can run without `respond.yaml` (previously confirmed only via manual testing).

distinguish missing respond.yaml from a misconfigured one

---

node/src/key_generation.rs
node/src/key_resharing.rs
node/src/mpc_client.rs
node/src/network.rs
node/src/network/computation.rs
node/src/network/conn.rs
node/src/network/constants.rs
node/src/network/indexer_heights.rs
node/src/p2p.rs
node/src/primitives.rs
node/src/protocol.rs
node/src/protocol_version.rs
node/src/sign.rs
node/src/triple.rs

Major changes:
* There are different kinds of network messages now:
* MpcMessage: can be Start, Computation(data), Abort(msg), Success. See #225 for definitions. Abort is used for both Abort and LeaderAbort in the definitions.
* IndexerHeightMessage: for syncing indexer heights, for #226 . This is exchanged and handled, but not used yet; that'll be left for a future PR focused on #226 .
* Implement leader-centric computations; make all MPC computations leader-centric:
* If leader fails, send Abort to everyone else.
* If follower fails, send Abort to leader.
* For triple and presignature generation, leader wait for followers to send Success before declaring itself success.
* TODO with next PR: Resolve #37 which is now very easy to do.
* Computations are now started explicitly with …

Implement leader-centric computation and indexer height network APIs.

---

Cargo.lock
deployment/Dockerfile-gcp

- Downgrading tempfile library to 3.14.0 as near indexer is crashing with 3.17.0
- Solve annoying TLS verification error 
`2025-03-10T10:04:02.827321Z  WARN telemetry: Failed to send telemetry data err=Connect(Io(Custom { kind: Other, error: "error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2104:" })) endpoint="https://telemetry.nearone.org/nodes"`

tempfile downgrade to 3.14

---

libs/chain-signatures/Cargo.lock
libs/chain-signatures/contract/Cargo.toml
libs/chain-signatures/contract/readme.md
libs/chain-signatures/contract/tests/updates.rs
libs/chain-signatures/contract/tests/user_views.rs
libs/chain-signatures/crypto-shared/Cargo.toml
libs/chain-signatures/crypto-shared/src/types.rs
pytest/tests/test_contract_hash.py

This PR is in support of #253, by
- introducing changes to the shared-crypto library;
- enabling the contract unittests by fixing the near-workspace dependency version.

contract dependencies and unittests

---

node/src/config.rs
node/src/key_generation.rs
node/src/key_resharing.rs
node/src/main.rs
node/src/mpc_client.rs
node/src/network.rs
node/src/p2p.rs
node/src/primitives.rs
node/src/protocol_version.rs
node/src/providers/mod.rs
node/src/sign.rs
node/src/triple.rs

This PR aims to create abstraction over signature schema.
Most of the changes are refactoring:
* Move existing implementations of `cait-sith`-related code into its `SignatureProvider` (namely, `triple.rs`, `presign.rs`, part of `hkdf.rs` and so on). 
The new logic introduced:
* `MpcClient` made responsible for distributing `MpcTaskId` to each `SignatureProvider`
* `KeyshareStorage` made compatible with any type of keyshare
* `KeyGeneration` and `KeyResharing` semantics does not do keyshare persisting now. This was lifted up into `Coordinator.rs` logic. The reason is because at the moment it's not clear how to handle `epoch` and introduction of new keys. More on that below[1].
What this PR should do, but doesn't (will be addressed in the future PRs):
* Different Database Schemas for each …

Abstract away Signature Schema

---

.github/workflows/ci.yml
deployment/Dockerfile-gcp
devnet/Cargo.lock
devnet/src/main.rs

The dockerfile used to use cargo-chef for incremental compilation. But now, our docker workflow doesn't really care about incremental compilation anymore because they are run on github actions anyway. Cargo-chef breaks on kevin's latest PR, for reasons that isn't worthwhile investigating. So I'm removing that and using standard rust compilation.
Also add rust-toolchain.toml which we should be having, add --locked to ensure versioning, and remove the need for .git. We don't need any of the submodules for compiling mpc-node.
Also while I'm at it, add devnet to the CI - otherwise some changes may cause Cargo.lock to change in that directory and we don't end up catching that.

Simplify Dockerfile, and add CI for devnet directory.

---

node/src/tests/mod.rs

I noticed that we generate a lot of assets (triples and presignatures) in integration tests and they consume a lot of resources. Reducing the amount of assets generated helps reduce flakiness in some integration tests

test: reduce flakiness by reducing the amount of assets buffered in tests

---

infra/scripts/generate_keys/Cargo.lock
infra/scripts/generate_keys/Cargo.toml
infra/scripts/generate_keys/src/main.rs

Removing unused cipher keys from generation.
Run example:
```
$ cargo run
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.03s
Running `target/debug/generate_keys`
p2p public key sign_pk: ed25519:CWNjbmqxnGMarFicw6ZqooP6HEfeAT4AJDmdaoEbKe1F
p2p secret key sign_sk: ed25519:2hnh9zTAkHheac8sjpkHFYqa2iWXEHot1qMv91C1EEGpiuUPJjnvuaQX6tW8vymFSxGnjMzsfggSi5M1N9aeRuSh
near account public key: ed25519:6r2NNPzyjKLCvVDAGdn3bT8KE79xH77uqYVat34VnHvQ
near account secret key: ed25519:h9xLEFM2LsxbiU9MvGqn9zzRszdDtLqwLisFDPbE8PyNQ15WieJ77sjhTK8mbPHLYk4shk4P8UBkCwsn9v2TMwv
near local encryption key: E4B0384CE696D59D15CAA03CE67AFAE6
```

Chores: removed unused cipher key generation

---

Cargo.lock
libs/chain-signatures/Cargo.lock
libs/chain-signatures/contract/Cargo.toml

There is a breaking change with the semver compatible version `5.9.0` of the `near-sdk` crate.
`5.9.0` of the crate depends on `v0.29.1` of `near-vm-runner` which in turn requires rustc `1.84` to compile:
```
Checking near-vm-runner v0.29.1
error[E0658]: raw address of syntax is experimental
--> /home/dsharifi/.cargo/registry/src/index.crates.io-6f17d22bba15001f/near-vm-runner-0.29.1/src/logic/gas_counter.rs:184:9
|
184 |         &raw mut self.fast_counter
|         ^^^^^^^^
|
= note: see issue #64490 <https://github.com/rust-lang/rust/issues/64490> for more information
For more information about this error, try `rustc --explain E0658`.
error: could not compile `near-vm-runner` (lib) due to 1 previous error
```
Pinning `near-sdk` to `5.2.1` allows us to avoid build failure when updating …

chore: pin `near-sdk` version to 5.2.1

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/coordinator.rs
node/src/keyshare/compat.rs
node/src/keyshare/gcp.rs
node/src/keyshare/local.rs
node/src/keyshare/mod.rs
node/src/keyshare/permanent.rs
node/src/keyshare/temporary.rs
node/src/keyshare/test_utils.rs
node/src/tests/mod.rs

This largely adheres to the specification for key storage in this design: https://docs.google.com/document/d/17y1lyyYwB5_iq8abv7A10XqAFjYtz8Ak83Wb3eH8j70/edit?tab=t.0
The strategy I've used here is to actually keep the implementation compatible with the rest of the code, so we can individually merge this PR while keeping the tests passing. However, **this is NOT a good version to actually release to anyone**, **NOR is it a proof or even a suggestion that we can implement this in a backwards-compatible way**, because:
* This will migrate the key storage format, so if anyone runs it in production, it will permanently alter their key storage. We might end up changing things before V2 is actually released, so this would not be good.
* For key import, the imported key *should* still be …

Implement multi-domain contract-coordinated key storage

---

libs/chain-signatures/contract/src/primitives/participants.rs
libs/chain-signatures/contract/src/primitives/test_utils.rs
libs/chain-signatures/contract/tests/common.rs
libs/chain-signatures/contract/tests/vote.rs

We don't need it at all anymore and we no longer need to be backwards compatible with V1 so just delete it.

Delete the cipher_pk field in contract V2.

---

devnet/src/cli.rs
devnet/src/mpc.rs

implementing vote_leave command to allow removing nodes from the cluster

Devnet: vote leave cmd

---

Cargo.lock
libs/chain-signatures/contract/Cargo.toml
libs/chain-signatures/contract/src/primitives/mod.rs
libs/chain-signatures/contract/src/primitives/participants.rs
libs/chain-signatures/contract/src/state/key_event.rs
node/Cargo.toml
node/src/indexer/fake.rs
node/src/indexer/participants.rs
node/src/tests/basic_cluster.rs
node/src/tests/faulty.rs
node/src/tests/resharing.rs

This will facilitate testing of multi-domain, and strengthen testing of keygen and resharing, as well as making eddsa testing work with the fake automatically.

Use real contract's logic in fake indexer.

---

Cargo.lock
libs/chain-signatures/contract/src/crypto_shared/types.rs
libs/chain-signatures/contract/src/state/key_event.rs
node/Cargo.toml
node/src/coordinator.rs
node/src/indexer/participants.rs
node/src/indexer/types.rs
node/src/key_events.rs
node/src/keyshare/compat.rs
node/src/keyshare/mod.rs
node/src/keyshare/test_utils.rs
node/src/mpc_client.rs
node/src/providers/ecdsa/key_resharing.rs
node/src/providers/ecdsa/mod.rs
node/src/providers/ecdsa/presign.rs
node/src/providers/ecdsa/sign.rs
node/src/providers/eddsa/mod.rs
node/src/providers/eddsa/sign.rs
node/src/providers/mod.rs
node/src/sign_request.rs
node/src/signing/debug.rs
node/src/signing/queue.rs

* Integrate Eddsa signature provider logic
* Make each signature provider store related keys. It's a questionable change. The other approach is to supply share when needed: when creating a signature, when setting-up background task, etc.. But for now it seems ok 
tests for eddsa will come in the follow-up PRs

eddsa integration 

---

node/src/assets.rs
node/src/cli.rs
node/src/coordinator.rs
node/src/indexer/fake.rs
node/src/indexer/participants.rs
node/src/indexer/types.rs
node/src/key_events.rs
node/src/p2p.rs
node/src/protocol_version.rs
node/src/providers/ecdsa/mod.rs
node/src/providers/ecdsa/presign.rs
node/src/providers/ecdsa/sign.rs
node/src/providers/ecdsa/triple.rs
node/src/tests/basic_cluster.rs
node/src/tests/faulty.rs
node/src/tests/mod.rs
node/src/tests/multidomain.rs
node/src/tests/resharing.rs

Inspired by @kuksag 's refactoring to put multiple domains into each signature provider, this goes all the way to make multidomain just work.
* Split presignature storage across domains by prefixing it by the `DomainId`. Add new test in the storage layer to check its behavior. Closes #287 .
* Make ecdsa signature provider have multiple presignature storages, one for each domain, and a corresponding background presignature generation task for each domain.
* Add `domain_id` to Presignature MpcTaskId. Bump protocol version since this is a network incompatible change.
* Fix #248 in the meantime, since the new store is no longer compatible with the old anyway. Also closes #312 since we'll start with empty DB.
* Fix a bug that the resharing computation was being passed an incorrect DomainConfig …

Make multidomain and multi-signature-scheme fully work.

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/coordinator.rs
node/src/indexer/types.rs
node/src/key_events.rs
node/src/keyshare/compat.rs
node/src/keyshare/mod.rs
node/src/keyshare/permanent.rs
node/src/keyshare/test_utils.rs
node/src/main.rs
node/src/providers/ecdsa/key_generation.rs
node/src/providers/ecdsa/key_resharing.rs
node/src/providers/ecdsa/mod.rs
node/src/providers/ecdsa/presign.rs
node/src/providers/ecdsa/sign.rs
node/src/providers/eddsa/kdf.rs
node/src/providers/eddsa/key_resharing.rs
node/src/providers/eddsa/mod.rs
node/src/providers/eddsa/sign.rs
node/src/providers/mod.rs
node/src/tests/benchmark.rs
node/src/tests/mod.rs
node/src/tests/research.rs

This PR is a follow-up after https://github.com/Near-One/cait-sith/pull/19
Changes include:
* Move from cait-sith style keygen struct to frost style
* Refactoring around eddsa signature
* Refactoring around Public key conversion into/from near sdk

Cait-sith follow-up refactoring

---

devnet/README.md
devnet/config.yaml.template
devnet/src/account.rs
devnet/src/funding.rs
devnet/src/loadtest.rs
devnet/src/mpc.rs
devnet/src/types.rs

This is to overcome testnet faucet not being available.
Tested and deployed a new cluster
```
➜  devnet git:(main) ✗ RUST_BACKTRACE=1 cargo run mpc and-upg new \
--num-participants 2 \
--threshold 1 \
--num-responding-access-keys 1 \
--near-per-responding-account 1
Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.16s
Running `target/debug/devnet mpc and-upg new --num-participants 2 --threshold 1 --num-responding-access-keys 1 --near-per-responding-account 1`
Going to create MPC network and-upg with 2 participants, threshold 1, 1 NEAR per account, and 1 additional access keys per participant for responding
Using provided funding account andrei-devnet.testnet from config
[andrei-devnet.testnet] Creating account mpc-0-and-upg-26b2094f1da5.andrei-devnet.testnet with …
```

Devnet: option to use own funding account

---

Cargo.lock
node/Cargo.toml

This is to fix the tempfile != 3.14 [issue]([#nearone/private > 2.5.0 Invalid cross-device link issue](https://near.zulipchat.com/#narrow/channel/308695-nearone.2Fprivate/topic/2.2E5.2E0.20Invalid.20cross-device.20link.20issue/with/504454634))
#15 39.15  [ Downloaded tempfile v3.14.0](https://github.com/Near-One/mpc/actions/runs/14273343466/job/40011339924)

tempfile 3.14

---

deployment/gcp-start.sh

Avoid hardcoding home dir when initializing near and mpc.
MPC_HOME_DIR is passed as an ENV var during docker container setup and should not be hardcoded to avoid issues whem someone uses other than /data home dir

Docker: MPC_HOME_DIR in image init script

---

libs/chain-signatures/contract/src/lib.rs
pytest/common_lib/contract_state.py
pytest/common_lib/shared.py
pytest/common_lib/signature.py
pytest/tests/test_contract_update.py
pytest/tests/test_key_event.py

add eddsa keygen and resharing pytest

---

libs/chain-signatures/contract/src/crypto_shared/kdf.rs
libs/chain-signatures/contract/src/crypto_shared/mod.rs
libs/chain-signatures/contract/src/crypto_shared/types.rs
libs/chain-signatures/contract/src/errors/impls.rs
libs/chain-signatures/contract/src/errors/mod.rs
libs/chain-signatures/contract/src/lib.rs
libs/chain-signatures/contract/tests/common.rs
node/src/providers/ecdsa/kdf.rs
node/src/providers/ecdsa/sign.rs

This PR removes the `ScalarExt` trait found in `libs/chain-signatures/contract/src/crypto_shared/types.rs`.
The trait was just a collection of wrapper functions around `k256::Scalar::from_repr` and `curve_25519::Scalar::from_repr`, with an added unwrap to it. This made it more complex than needed, and a source of panic that was not obvious when testing.

refactor: Remove `ScalarExt` trait

---

libs/chain-signatures/Cargo.lock
libs/chain-signatures/contract/Cargo.toml

In contract integration tests, `respond` for both ecdsa and eddsa signatures consume a lot of gas and for eddsa signatures they sometimes fail due to running out of gas. The reason is that the near workspace version is outdated and it doesn't contain [this fix](https://github.com/near/nearcore/pull/12192). After this fix, `respond` call for eddsa signatures consume ~7.5Tgas.

fix gas usage problem in contract integration tests

---

pytest/common_lib/shared.py
pytest/tests/test_web_endpoints.py

Signature requests pass for EdDSA.
Tested with:
```bash
pytest tests/test_signature_request.py
```

test: enable EdDSA signature requets in pytests

---

devnet/src/cli.rs
devnet/src/mpc.rs
devnet/src/terraform.rs
devnet/src/terraform/describe.rs
libs/chain-signatures/contract/src/primitives/domain.rs
libs/chain-signatures/contract/src/primitives/key_state.rs
libs/chain-signatures/contract/src/primitives/participants.rs
libs/chain-signatures/contract/src/state/key_event.rs

Example description:
```
MPC contract deployed at: mpc-contract-and-upg-4df70f9abb68.b892843ed20d.testnet
Contract is in Running state
Epoch: 9
Keyset:
Domain 0: Secp256k1, key from attempt 0
Domain 1: Ed25519, key from attempt 0
Domain 2: Secp256k1, key from attempt 0
Domain 3: Ed25519, key from attempt 0
Domain 4: Secp256k1, key from attempt 0
Domain 5: Ed25519, key from attempt 0
Parameters:
Participants:
ID 3: mpc-2-and-upg-c4c3bbdf00c0.andrei-devnet.testnet (http://mpc-node-2.service.mpc.consul:3000)
ID 4: mpc-1-and-upg-5a31c3d4ec91.andrei-devnet.testnet (http://mpc-node-1.service.mpc.consul:3000)
ID 5: mpc-0-and-upg-26b2094f1da5.andrei-devnet.testnet (http://mpc-node-0.service.mpc.consul:3000)
Threshold: 3
Nomad server: http://35.203.145.20
Nomad client #0: zone us-west1-b, instance …
```

Add CLI command to describe MPC cluster in devnet tool

---

Cargo.lock
node/Cargo.toml
node/src/coordinator.rs
node/src/indexer/mod.rs
node/src/indexer/participants.rs
node/src/indexer/real.rs
node/src/indexer/tx_sender.rs
node/src/network.rs
pytest/common_lib/shared.py
rust-toolchain.toml

Also fix:
* Coordinator busy loops forever if indexer crashes. (We found it!)
* pytest used incorrect serialization of ed25519 secret key. (How did it work before?)

Upgrade nearcore to 2.6.0-rc.1.

---

devnet/README.md
devnet/src/cli.rs
devnet/src/constants.rs
devnet/src/loadtest.rs
devnet/src/mpc.rs
devnet/src/terraform.rs
devnet/src/types.rs

- Update README (defaulting to instructions for testing V2, but including legacy V1 instructions).
- Introduce constants for docker image, contract path, and parallel signing contract path, to use as defaults. When we release V2, we should update these.
- Make `deploy-contract` command use the correct `init()` parameters for V2.
- Support parallel signing contract V2.
- Move `threshold` parameter to the `deploy-contract` call; it makes more sense there.

Update README for devnet V2; tie loose ends for devnet V2.

---

libs/chain-signatures/contract/src/lib.rs
libs/chain-signatures/contract/src/storage_keys.rs
libs/chain-signatures/contract/src/update.rs
libs/chain-signatures/contract/tests/common.rs
libs/chain-signatures/contract/tests/updates.rs

Resolves #329
Resolves #318
* Accept update proposals which are only modifies code, or config, but not both.
* A participant's vote can be counted only once for some proposal. If participant votes again, transfer vote from one proposal to the other
* Remove all proposals after update
* Add tests for introduced code paths

Smart contract "proposal updates" logic improvements

---

devnet/Cargo.toml
devnet/src/mpc.rs
libs/chain-signatures/contract/Cargo.toml
libs/chain-signatures/contract/src/lib.rs
libs/chain-signatures/contract/src/primitives/votes.rs
libs/chain-signatures/contract/src/state/initializing.rs
libs/chain-signatures/contract/src/state/key_event.rs
libs/chain-signatures/contract/src/state/mod.rs
libs/chain-signatures/contract/src/state/resharing.rs
libs/chain-signatures/contract/src/state/running.rs
libs/chain-signatures/contract/src/utils.rs
node/Cargo.toml
node/src/cli.rs
node/src/indexer/participants.rs
node/src/indexer/real.rs
node/src/tests/mod.rs
node/src/web.rs
pytest/tests/test_web_endpoints.py

This PR exposes a new web endpoint `debug/contract`, that displays the current contract view of an mpc node..
It uses the logic introduced in https://github.com/Near-One/mpc/pull/351 to stringify the current ProtocolState instance and moves this logic to the contract folder (behind a `dev-utils` feature flag).
follow-ups:

Add web endpoint /debug/contract

---

node/src/indexer/handler.rs
node/src/indexer/real.rs

The indexer thread should terminate if the channel it sends block updates to is closed, as this is an unrecoverable event.

fix: return early in Indexer thread and `listen_blocks` if channel to MPC node is closed.

---

node/src/signing/metrics.rs
node/src/signing/queue.rs

We added a latency metric for sign requests in terms of number of blocks between a sign and response was seen on chain #366.
This PR adds the same metric, but measures the latency in absolute duration.
https://github.com/Near-One/mpc/pull/366#pullrequestreview-2764916681

chore: Add metrics for latency of signature request responses in seconds

---

node/src/cli.rs
node/src/indexer/handler.rs
node/src/indexer/real.rs

We have a `spawn_blocking` that wraps the join_handle in `spawn_real_indexer`. This is presumably done to await on the `std::thread::JoinHandle` returned from the spawned indexer.
The `spawn_blocking` call lead to the issue we saw the other day with the binary not exiting, because the runtime is unable to drop this task since it never terminates. We can remove this `spawn_blocking call`, and use a [oneshot channel](https://docs.rs/tokio/latest/tokio/sync/oneshot/fn.channel.html) instead that the indexer thread can respond on if it exits.
In general  oneshot channels are a good practice to use when communicating from a synchronous threads to an async task.

chore: remove spawn_blocking call wrapping the indexer thread

---

Cargo.lock
node/Cargo.toml
node/src/signing/debug.rs
node/src/signing/queue.rs
node/src/signing/recent_blocks_tracker.rs

Followup to #366 and #373, the block height as well as indexed time used was incorrect - we should use the block that contains the signature response, which was being held until it becomes final, instead of the block that triggers the finalization of such a block.
Fixing this required some slight modification to the data structures.
Also, use the clock instead of `Instant::now()` for getting instants. Also add a test that the metrics are correctly computed.

Correctly export signature latency metrics.

---

Cargo.lock
devnet/Cargo.lock
libs/chain-signatures/Cargo.lock
libs/chain-signatures/contract/Cargo.toml
libs/chain-signatures/contract/src/lib.rs

Fix to [this discussion](https://nearone.slack.com/archives/C07UW93JVQ8/p1746013523358199?thread_ts=1746005094.777519&cid=C07UW93JVQ8):
- adjust the gas attachment so we don't run out of gas on failure
- move the cleaning mechanism into the `respond` call. This should allow us to remove the hanging request on testnet, but might have its own set of problems.

[Fix] Adjust gas attachment

---

libs/chain-signatures/contract/readme.md
libs/chain-signatures/contract/src/lib.rs
pytest/tests/test_contract_update.py

Unfortunately, the cleanup function that was supposed to clear the state from timed out requests ran out of gas (c.f. #380 ).
This means that any signature requests that timed out since the latest release will remain in the state indefinitely, preventing the user from submitting the same request again.
This PR allows the user to re-submit signature requests. This guarantees to remove the request from the state, because:
- either the MPC network will submit a signature response and remove the request from the state,
- or the request will time out and be removed from the state in the cleanup function.
**But beware!** Re-submitting the same request before the time-out duration of 200 blocks has passed, or a response has been submitted, risks to result in another timed-out request. That is …

accept re-submitting requests

---

Cargo.lock
node/Cargo.toml

Apply Robin's #389 to `main`. It is in [testnet-release](https://github.com/Near-One/mpc/tree/testnet-release) at the moment

Hotfix for cait-sith memory leak.

---

node/src/cli.rs

CLI import-export keyshare got broken when keyshare format changed.
Fixing this here

CLI: Fix import keyshare 

---

node/src/network/constants.rs
node/src/p2p.rs

Trying to address https://github.com/Near-One/mpc/issues/388 by adding a 30 seconds timeout for incoming connections.
Docker freeze container at 14:10:05 to simulate a process hang like we had in testnet:
```
andrei@tcptime-nomad-mpc-client-1:~$ sudo docker pause b35c3d2b91a7
b35c3d2b91a7
```
Exactly after 30 seconds logs start reporting computation errors and handle connection 30 seconds::
```
2025-05-22T14:10:30.833307Z  INFO stats: #197970541 HeqBED9iK17ogAtuH7SY2BChXTWtQYgWfprkodTX2kKT 29 validators 10 peers ⬇ 780 kB/s ⬆ 546 kB/s 1.60 bps 14.3 Tgas/s CPU: 25%, Mem: 28.1 GB
2025-05-22T14:10:32.796372Z  INFO indexer: # 197970545 | Blocks processing: 0| Blocks done: 1587. Bps 1.70 b/s 
2025-05-22T14:10:35.328034Z ERROR mpc_node::tracking: Task failed: deadline has elapsed; trace:
from …
```

30s timeout for incoming connections

---

libs/chain-signatures/rust-toolchain.toml

fix the rust toolchain:
```
error: 'cargo-clippy' is not installed for the toolchain '1.85.1-x86_64-unknown-linux-gnu'.
To install, run `rustup component add --toolchain 1.85.1-x86_64-unknown-linux-gnu clippy`
```

toolchain fix

---

libs/chain-signatures/contract/src/lib.rs
libs/chain-signatures/rust-toolchain.toml

The contract still seems to run [out of gas](https://testnet.nearblocks.io/txns/GNWMQfbdPAkBYH5hsLy4mqhsCPoSvUrZHibUKvfG7TN3?tab=execution#CJdLFzGkvUYitWGUQ14oG8UZzc8vUiPkxXWjPvQ2q6n2) when a signature request fails.
Since #380, we successfully remove the transaction from the contract state, but now run out of gas in the very last step `fail_on_timeout`.
This is not a pressing issue, because this will not result in any inconsistent state and the final execution outcome is still a failure, which is desirable.
However, might be good to fix this with the next release.

adjust prepaid gas in contract

---

.github/workflows/ci.yml
.github/workflows/pr-title-lint.yml
CHANGELOG.md
cliff.toml

- closes #491 
This PR introduces an initial changelog, generated using `git-cliff`. Additionally, I've added a CI check to enforce the usage of conventional commits going forward. This will allow us to generate useful changelogs directly from our commit history for future releases.

chore: Initial Changelog + CI check

---

libs/chain-signatures/contract/src/errors/impls.rs
libs/chain-signatures/contract/src/errors/mod.rs
libs/chain-signatures/contract/src/lib.rs
libs/chain-signatures/contract/src/primitives/participants.rs
libs/chain-signatures/contract/src/state/running.rs
libs/chain-signatures/contract/src/v0_state/mod.rs
libs/chain-signatures/contract/tests/common.rs
libs/chain-signatures/contract/tests/sign.rs
libs/chain-signatures/contract/tests/tee.rs
libs/chain-signatures/contract/tests/user_views.rs
node/src/indexer/fake.rs
node/src/indexer/tx_sender.rs
node/src/indexer/types.rs
node/src/metrics.rs
node/src/mpc_client.rs

Resolves #424:
This PR introduces a new unprotected endpoint: `verify_tee`.
The purpose of this endpoint is to assess the current TEE status of all participants and take corrective action if necessary:
- If `threshold` or more participants have a `Valid` or `None` TEE status:
- A re-sharing is triggered, excluding participants with an `Invalid` status, preserving the current threshold.
- If fewer than `threshold` participants have a `Valid` or `None` TEE status:
- The contract stops accepting new signature requests until enough participants update their status and `verify_tee` is called again.
Note that this endpoint can only be called while the protocol is in running state.
(not sure about where to place the background task in the node @near-bookrock any suggestions?)
Requires additional …

feat(Tee): Automatic kickout mechanism for invalid TEE status

---

.gitignore
pytest/common_lib/shared/__init__.py
pytest/common_lib/shared/mpc_cluster.py
pytest/common_lib/shared/mpc_node.py
pytest/common_lib/shared/near_account.py

resolves #523 
Before this PR, pytest used the same `signer_key` that was used by the MPC nodes. This resulted in occasional nonce conflicts among the MPC nodes (c.f. #523 ).
In this PR, we generate additional access keys for the mpc node accounts. These keys are used exclusively by the pytest framework (for initiating resharing, initializations, voting on updates etc.).
Note that we do not need to generate additional access keys for the contract accounts, as those are already exclusive to the pytest framework. Any conflicts occurring on that side must be handled through a more elaborate nonce tracking mechanism (not necessary for now).

test(pytest): resolve pytest nonce conflicts

---

devnet/src/cli.rs
devnet/src/mpc.rs
devnet/src/terraform.rs
devnet/src/types.rs

Requires https://github.com/Near-One/infra-ops/pull/476

feat(devnet): enable ssd support

---

deployment/Dockerfile-gcp

The docker build and publish action is currently broken on`main`. The issue that the `devnet` package recently became a part of the workspace, but in the docker file we forgot to include the directory its defined in to the build action.
This PR includes copying the`devnet`directory in the build action docker file.
Link to failed action on main https://github.com/near/mpc/actions/runs/15872850961/job/44753339713
```
9.054 Caused by:
9.054   failed to read `/app/devnet/Cargo.toml`
```
Verified that it works with these changes:
https://github.com/near/mpc/actions/runs/15873852911

ci: fix docker build and publish action

---

libs/chain-signatures/contract/src/tee/tee_participant.rs

This fix addresses a code review comment from the Trail of Bits audit. In the future, we should implement a more comprehensive and explicit process for setting a minimum TCB level for all deployed nodes.
Fixes #581.

fix(tee): Ensure quote verification status is `UpToDate`

---

node/src/indexer/mod.rs
node/src/indexer/real.rs

Added the `stats` property to the `IndexerState` struct in mod.rs and removed it from real.rs.

chore: migrated stats into IndexerState

---

.github/workflows/ci.yml
node/Cargo.toml
node/src/config.rs
node/src/indexer/handler.rs
node/src/indexer/real.rs
node/src/indexer/tx_sender.rs
node/src/tests/faulty.rs
node/src/tests/mod.rs
node/src/tests/resharing.rs
pytest/common_lib/constants.py
pytest/common_lib/shared/__init__.py
pytest/common_lib/shared/mpc_cluster.py
pytest/common_lib/shared/mpc_node.py
pytest/exec_pytest.sh
pytest/readme.md
pytest/tests/test_lost_assets.py

- a pytest for https://github.com/near/mpc/pull/595
- the ability to simulate network hardship for the indexer.
Additionally, resolves https://github.com/near/mpc/issues/561
The binary can now be compiled with the feature `--network-hardship-simulation`. If done so, then the indexer will read the contents of a file `listen_blocks.flag`, located in the home directory of the node.
If the the file exists, then it must contain a boolean value. If that value is `false`, then the indexer will stop ingesting blocks, simulating an error similar to what we encountered on mainnet.
This feature can be used to test the fix introduced in #595 in pytests, testnet or mainnet clusters
If we need to put https://github.com/near/mpc/issues/592 on hold or not implement it at all, due to constants of our TEE …

feat: enable network hardship simulation

---

node/src/p2p.rs
node/src/tests/faulty.rs

Backport of fix from https://github.com/near/mpc/pull/600/commits/00a7d1816e70a6ef2e63ab94907dd35356c36f79 to prevent the test from hanging up

fix: Use separate port seed for indexer stuck test

---

deployment/gcp-start.sh

After #445 we generate responder keys inside a node, thus we no longer read values from `respond.yaml` config, that was supplying the keys and the responder account id.
Responder account id field migrated into `config.yaml`.
This PR brings back default behaviour when responder id wasn't specified + sets the value in the config

chore: add `near_responder_id` and number of responder keys in `gcp-start.sh` logic

---

Cargo.lock
libs/chain-signatures/contract/Cargo.toml
node/Cargo.toml
node/src/indexer/mod.rs
pytest/common_lib/shared/__init__.py

Closes #614 
Equivalent to https://github.com/near/mpc/pull/603 for `testnet-release`

chore: bump nearcore to `2.7.0-rc.2`

---

node/src/tee/remote_attestation.rs

fix(tee): don't re-encode tdx_quote to hex

---

node/src/tee/remote_attestation.rs

fix(tee): serialize `quote_collateral` to a `serde_json::Value` instead of String

---

node/src/indexer/real.rs
node/src/indexer/tee.rs

closes https://github.com/near/mpc/issues/661

chore: do not wait for indexer sync before generating TEE attestation

---

libs/chain-signatures/contract/src/v0_state/mod.rs
libs/chain-signatures/contract/tests/updates.rs
pytest/common_lib/shared/mpc_cluster.py

chore: use the right `protocol_state` type for MpcContractV1 state

---

node/src/metrics.rs
node/src/network.rs
node/src/network/indexer_heights.rs
pytest/common_lib/shared/metrics.py
pytest/common_lib/shared/mpc_cluster.py
pytest/common_lib/shared/mpc_node.py
pytest/tests/test_lost_assets.py

feat(metrics): Expose peers block height metric

---

.github/workflows/tee_launcher.yml
tee_launcher/development/Dockerfile.launcher

#685 follow-up
This PR: 
1. Pins debian package repository, otherwise you can't build it as of now
2. Fixes how git refs are handled in ci, because it didn't get propagated on a push

chore: Fix failing CI for TEE Launcher build

---

node/src/network.rs

The function: 
```
pub fn select_random_active_participants_including_me(
&self,
total: usize,
peers_to_consider: &[ParticipantId],
) -> anyhow::Result<Vec<ParticipantId>>
```
Should return `total` number of online participants amongst `peers_to_consider`, including the caller participant. 
This function has two usages:
1. In generation of triples
2. In generation eddsa signatures
This function behaves incorrectly, when the size of `peers_to_consider` is insufficient, to make up for `total` participants.
Extrapolated example: if we pass empty `peers_to_consider`. In that case `[me]` will be returned, because `me` is getting appended regardless. The error should be returned instead.
`IteratorRandom::choose_multiple(_, amount)` silently returns less than `amount` elements, if there are not …

fix: Adjust invariant checks when selecting participants

---

tee_launcher/launcher-docker-compose.yaml

chore: Specify TEE Launcher image from `nearone` registry

---

node/src/web.rs

resolves https://github.com/near/mpc/issues/709
This should not yet be a breaking change, so it should be pretty safe to do.

chore: rename web endpoint /get_public_data to /public_data

---

devnet/README.md
devnet/src/account.rs
devnet/src/cli.rs
devnet/src/mpc.rs
devnet/src/terraform.rs
devnet/src/types.rs
node/src/config.rs

resolves #521 
requires https://github.com/Near-One/infra-ops/pull/503
related follow-ups:
- https://github.com/near/mpc/issues/710
- https://github.com/near/mpc/issues/712
changes:
- `deploy-contract` command is now split into two commands `deploy-contract` (deploy the code) and `init-contract` (initialize the contract).
- `add-keys` method, adding the public keys generated by the nodes to the mpc and responder accounts (signer and responder keys).
- unused `--max-requests-to-remove` argument has been removed from the contract commands
- devnet no longer panics upon calling `describe` in case the contract is not initialized:
```
thread 'main' panicked at devnet/src/mpc.rs:812:10:
Expected rpc node to respond: ServerError(HandlerError(ContractExecutionError { vm_error: "wasm execution …
```

fix(devnet): compatibility with upcoming mpc node version 3.0.0

---

Cargo.toml
node/src/lib.rs
node/src/main.rs

Closes #719
This PR simply moves the definition of all crates in `main.rs` to `lib.rs`. We can definitely iterate further on the distinction between the two, but this at least enables reusing MPC node modules outside of the binary for e.g. the Devnet CLI and potentially other benchmarks or external integration tests.

chore: Move MPC node modules to `lib.rs`

---

Cargo.lock
node/Cargo.toml
node/src/cli.rs
node/src/tee/allowed_image_hashes_watcher.rs

fix: defer creating `allowed_image_hash` file until write

---

.github/workflows/python-code-quality.yml

chore: execute python lint/format CI only when needed

---

.github/workflows/ci.yml

Resolves https://github.com/near/mpc/issues/696
Reduces CI time by approx. 20 minutes.
Additionally, we now also unittest the build without the tee flag.
@andrei-near I think we need to change the branch protection rules to allow this PR to pass (c.f. [this thread](https://github.com/orgs/community/discussions/26698#discussioncomment-3252954))

chore(ci): split ci-tests into multiple jobs

---

node/src/network.rs

fix: node ignores peers lagging 50 blocks behind

---

Cargo.lock
Cargo.toml

This contributes with #741
It should avoid depending on protobuf v2.*, fixing https://github.com/near/mpc/security/dependabot/18

chore: remove default features prometheus

---

node/src/indexer/configs.rs
node/src/metrics.rs
node/src/network.rs
node/src/network/indexer_heights.rs

The goal of this PR is to port all fixes deployed to mainnet release branch over to the testnet release:
* https://github.com/near/mpc/pull/743
**Methodology:**
Since we don't have a list of when which fixes where applied, I looked at the commit history of testnet-release and mainnet-release branch
https://github.com/near/mpc/commits/testnet-release/  and https://github.com/near/mpc/commits/mainnent-release/
**Mainnet fixes not on main and not on testnet-release:**
* https://github.com/near/mpc/pull/556
* included in testnet with https://github.com/near/mpc/pull/600
* https://github.com/near/mpc/pull/803
* included in testnet with https://github.com/near/mpc/pull/804
* https://github.com/near/mpc/pull/554
* included in tesnet with https://github.com/near/mpc/pull/371/files
* …

chore: port mainnet fixes to testnet branch

---

Cargo.lock
attestation/Cargo.toml
attestation/src/report_data.rs
attestation/tests/common.rs
attestation/tests/test_attestation_verification.rs
libs/chain-signatures/Cargo.lock
libs/chain-signatures/contract/src/tee/tee_state.rs

chore: remove `near_crypto` from attestation crate

---

libs/chain-signatures/contract/src/lib.rs
libs/chain-signatures/contract/src/tee/tee_state.rs

fix(tee): ensure participants run valid TEE or none

---

libs/chain-signatures/Cargo.lock
libs/chain-signatures/contract/Cargo.toml
libs/chain-signatures/contract/tests/common.rs

chore: remove `near_crypto` dependency from smart contract

---

libs/chain-signatures/contract/src/crypto_shared/types.rs
libs/chain-signatures/contract/src/crypto_shared/types/serializable.rs
libs/chain-signatures/contract/src/primitives/test_utils.rs

Closes #757 
This PR simplifies the serialization trait implementations for `PublicKeyExtended` by using `SerializableEdwardsPoint` consistently throughout the module. Additionally, I've broken out the `serialize` submodule to a separate file and implemented more useful traits on the `SerializableEdwardsPoint` type to make using it more ergonomic.
Note: I considered replacing other usages of `EdwardsPoint` with `SerializableEdwardsPoint` in the rest of the code base but I don't see the (Edwards) point of doing that, so I let it be for now.

refactor: Consistent usage of SerializableEdwardsPoint in crypto_shared/types.rs

---

Cargo.lock
crates/contract_history/Cargo.toml

fix: Add missing bs58 dependency in contract_history crate

---

.github/workflows/ci.yml

ci: remove redundant and duplicate clippy check for `devnet` crate

---

node/src/indexer/real.rs
node/src/indexer/tx_sender.rs

From PR conversation: https://github.com/near/mpc/pull/1101#discussion_r2348748429

refactor: Send indexer state as arg instead of oneshot

---

Cargo.lock
Cargo.toml

ci: pin serde to `1.0.2191` to fix compilation issue with `dstack-sdk`

---

Cargo.lock
Cargo.toml

Follow up to #1126 
`dstack-sdk` has a new version released that bumps their alloy version.

chore(deps): bump `dstack-sdk` and remove serde pin

---

crates/contract/src/lib.rs
crates/contract/src/primitives/participants.rs
crates/contract/src/tee/tee_state.rs
crates/contract/tests/common.rs
crates/contract/tests/expired_attestation.rs
crates/contract/tests/integration_tee_cleanup_after_resharing.rs
crates/contract/tests/tee.rs

Resolves #1084, #1119 and #1145
Introduces `NodeUid` as a unique identifier for participants nodes.
```rust
pub struct NodeUid {
/// Operator account
pub account_id: AccountId,
/// TLS public key
pub tls_public_key: PublicKey,
}
```
Reasonable assumptions about the network state are:
1. Each node operator is uniquely identified by their `AccountId` (existing assumption).
2. A node operator may only have one participating node at any point in time (enforced by the `Participants` struct).
3. A node operator may have multiple nodes submitting an attestation to the contract (enabled by this PR);
4. Each node is uniquely identified by their `tls_public_key` (not really enforceable on the contract).
Note that the following give probabilistic guarantees for point 4, if nodes run inside TEEs:
- a …

chore: index nodes by account id & TLS key in TEE State

---

crates/node/src/tee/allowed_image_hashes_watcher.rs

closes #1078
Error message was previously misleading. No shutdown signal is being sent if the node detects that the image it is currently running is not allowed.

chore: update error message in image hash watcher

---

crates/devnet/README.md
crates/devnet/src/constants.rs
crates/test_parallel_contract/src/lib.rs

Closes #1158 
Results:
```shell
❯ mpc-devnet mpc $MPC_NETWORK_NAME describe
MPC contract deployed at: mpc-contract-gilcu3ssd-test-7f718377a326.64204c0b3b36.testnet
Contract is in Running state
Epoch: 0
Keyset:
Domain 0: Secp256k1, key from attempt 0
Domain 1: Ed25519, key from attempt 0
Domain 2: CkdSecp256k1, key from attempt 0
Parameters:
Participants:
ID 0: mpc-0-gilcu3ssd-test-1f4950e8e33a.64204c0b3b36.testnet (http://mpc-node-0.service.mpc.consul:3000)
ID 1: mpc-1-gilcu3ssd-test-7bbcf2acd5d4.64204c0b3b36.testnet (http://mpc-node-1.service.mpc.consul:3000)
Threshold: 2
Nomad server: http://34.83.44.14
Nomad client #0: zone us-west1-b, instance type n2d-standard-8, debug: http://35.233.216.2:8080/debug/tasks
Nomad client #1: zone us-west1-b, instance type n2d-standard-8, debug: …
```

chore: make sure devnet tests ckd

---

crates/contract/src/primitives/key_state.rs
crates/node/src/keyshare.rs
crates/node/src/keyshare/permanent.rs
crates/node/src/keyshare/test_utils.rs
crates/node/src/tests.rs
crates/node/src/tests/changing_participant_details.rs

**Resolves #1213**
This PR includes additional improvements as outlined below (valid on their own, but pretty necessary with #1214 in mind).
**Enforce consistency of keyshares in `PermanentKeyStorage` across different epochs:**
This PR fixes a slight oversight in `PermanentKeyStorage::store()`. Until now, it was possible to have inconsistent keyshares in `PermanentKeyStorage`, e.g. to have two keyshares for the same domain (but different epoch), that have different public keys.
It was not a real issue, because we only store the keyshares to the permanent keyset when the contract enters a running or resharing state. But nonetheless, it seemed diligent to add a consistency check to the `PermanentKeyStorage`, to enforce local consistency.
**Make implicit assumptions on …

feat: import keyshares into empty keyshare storage
