near/mpc

- .github/workflows/test.yml
> feat: add simple CI

- Cargo.lock
- mpc-recovery/Cargo.toml
- mpc-recovery/src/actor.rs
- mpc-recovery/src/lib.rs
- mpc-recovery/src/main.rs
- mpc-recovery/src/web.rs
> feat: add tracing-based logging

- Cargo.lock
- integration-tests/Cargo.toml
Workspaces released a version with all the features we need.
> workspaces version

- flake.lock
- flake.nix
We are apparently using a new mac component, probably pulled in by openssl
> Fixed the nix deps

- contract/.cargo/config.toml
Just a little quality of life thing
> Make the contract build wasm by default

- infra/modules/signer/main.tf
- infra/mpc-recovery-prod/backend-config-prod.tfvars
- infra/mpc-recovery-prod/main.tf
- infra/mpc-recovery-prod/variables.tf
- infra/mpc-recovery-testnet/backend-config-prod.tfvars
- infra/mpc-recovery-testnet/main.tf
- infra/mpc-recovery-testnet/variables.tf
- infra/partner/main.tf
- infra/partner/template.tfvars
- infra/partner/variables.tf
Cleaned up infra folder to delete irrelevant stuff and brought partner scripts up to date
> chore: cleanup infra

- node/src/protocol/mod.rs
Minor fix when handling protocol error out on progression
> fix: Protocol loop should continue on error

- Cargo.lock
- contract/src/lib.rs
- integration-tests/Cargo.toml
- integration-tests/tests/multichain/mod.rs
- node/Cargo.toml
- node/src/indexer.rs
- node/src/kdf.rs
- node/src/lib.rs
- node/src/protocol/cryptography.rs
- node/src/protocol/message.rs
- node/src/protocol/signature.rs
- node/src/util.rs
> feat: implement key derivation

- infra/multichain-prod/main.tf
- infra/multichain-prod/variables.tf
- infra/multichain-testnet/main.tf
- infra/multichain-testnet/variables.tf
Mostly copy pasted from multichain-dev
> create terraform for multichain testnet and prod

- infra/modules/multichain/main.tf
- infra/modules/multichain/variables.tf
- infra/multichain-dev/main.tf
- infra/multichain-dev/terraform-dev.tfvars
- infra/multichain-dev/variables.tf
- infra/multichain-prod/main.tf
- infra/multichain-prod/variables.tf
- infra/multichain-testnet/main.tf
- infra/multichain-testnet/variables.tf
Changes to params in our Start command in node/src/cli.rs require an update to terraform.
Plus I've redeployed our contract on multichain-testnet-2.testnet to accomodate the changes in contract/
> fix terraform multichain

- infra/multichain-vm-dev/main.tf
- infra/multichain-vm-dev/terraform-dev.tfvars
- infra/multichain-vm-dev/variables.tf
- infra/multichain-vm-testnet/main.tf
- infra/multichain-vm-testnet/variables.tf
1) remove s3_url env var from dev 
2) remove address env duplicate assignment
3) remove address from node_configs
> fix: vm terraform minor fixes

- integration-tests/README.md
> Added a missing step to the integration tests instructions

- node/src/protocol/triple.rs
> fix: stockpile condition

- Cargo.lock
- integration-tests/Cargo.toml
- node/Cargo.toml
- node/src/protocol/presignature.rs
Lot's of security fixes and I believe triple generation messages should be 50% smaller.
> Switched over to a newer version of cait sith

- node/src/metrics.rs
- node/src/protocol/consensus.rs
- node/src/protocol/cryptography.rs
- node/src/protocol/presignature.rs
- node/src/protocol/signature.rs
I added a field my_account_id to PresignatureManager so that it's easier for me to add metrics
> add more metric

- node/src/cli.rs
- node/src/metrics.rs
- node/src/protocol/mod.rs
easier to monitor contract version changes.
> add metric for contract version 

- node/src/http_client.rs
- node/src/metrics.rs
- node/src/protocol/mod.rs
- node/src/types.rs
This also includes metrics from @ChaoticTempest 's PR
This was what's running in our dev
> Add send_encrypted metric

- .github/workflows/multichain-dev.yml
> Feat: dev deployment pipeline

- contract/src/lib.rs
- integration-tests/tests/multichain/actions/wait_for.rs
There are no real changes here. Should help external developers to navigate the API.
> Contract API and other functions grouped

- chain-signatures/contract/src/lib.rs
- integration-tests/chain-signatures/tests/actions/wait_for.rs
This makes the contract use less state for yield resume
> chore: Remove unnecessary state from contract

- integration-tests/chain-signatures/Cargo.lock
- load-tests/Cargo.lock
Executed `cargo update -p time`.
> Fix cargo check

- chain-signatures/node/src/indexer.rs
60s to restart the indexer might be too fast for mainnet and testnet. Bump up the waiting time for restarting the indexer to 5mins
> fix: bump indexer to 5mins instead of 60s

- .github/workflows/deploy-prod.yml
I have created a "prod" environment in the MPC repo and added Kody, David and Xiangyi as approvers for running this github actions workflow
> adding environment for deployment protection

- chain-signatures/node/src/http_client.rs
- chain-signatures/node/src/mesh/connection.rs
- integration-tests/chain-signatures/Cargo.lock
This is so we can cut the release faster and do the code reviews for refactoring with ease
> remove timeout for send encrypted and /state
